DROP SCHEMA IF EXISTS api           CASCADE;
DROP SCHEMA IF EXISTS dev           CASCADE;
DROP SCHEMA IF EXISTS reclada       CASCADE;
DROP SCHEMA IF EXISTS reclada_notification CASCADE;
DROP SCHEMA IF EXISTS reclada_object CASCADE;
DROP SCHEMA IF EXISTS reclada_revision CASCADE;
DROP SCHEMA IF EXISTS reclada_storage CASCADE;
DROP SCHEMA IF EXISTS reclada_user  CASCADE;